name: maps
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python and CUDA
  - python=3.10
  - cudatoolkit=11.8
  
  # PyTorch ecosystem
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - torchmetrics
  
  # Scientific computing
  - numpy
  - pandas
  - scikit-learn
  - networkx
  
  # Deep Learning tools
  - transformers
  - bitsandbytes
  - peft
  - sentencepiece
  - protobuf
  - wandb
  - datasets
  
  # Utilities
  - tqdm
  - ipykernel
  - pytables
  - h5py
  - gym
  
  - pip
  - pip:
    # Dependencies that are better installed via pip
    - flash-attn
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv